version: '2.1'

services:
  hello:
    image: sam016/go-watcher:latest
    command: watcher -f /go/src/hello/watcher.yml
    ports:
      - "7000:7000"
      - "2345:2345"
    environment:
      - GO_VERSION=1.11
    volumes:
      - ./hello:/go/src/hello
